config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
  validates :name, presence: true
  validates :address, presence: true
  validates :description, presence: true, length: { minimum: 50 }
  validates :price_per_night, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1 }
  validates :number_of_guests, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: %i[show edit update destroy]

  # GET /flats
  def index
    @flats = Flat.all
  end

  # GET /flats/1
  def show
  end

  # GET /flats/new
  def new
    @flat = Flat.new
  end

  # GET /flats/1/edit
  def edit
  end

  # POST /flats
  def create
    @flat = Flat.new(flat_params)

    if @flat.save
      redirect_to @flat, notice: "flat was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /flats/1
  def update
    if @flat.update(flat_params)
      redirect_to @flat, notice: "flat was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /flats/1
  def destroy
    @flat.destroy
    redirect_to flats_url, notice: "flat was successfully destroyed.", status: :see_other
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_flat
    # finds the flat with the id in the URL
    @flat = Flat.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def guests_icon
    '<i class="fas fa-user"></i>'.html_safe
  end

  def british_pound_icon
    '<i class="fa-solid fa-sterling-sign"></i>'.html_safe
  end
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_flat.html.erb
<div id="<%= dom_id flat %>">
  <div class="flat-card-content">
    <div class="flat-index-card">
      <div class="flat-card-title">
        <h4><%= flat.name %></h4>
      </div>
      <p>
        <%= flat.address %>
      </p>
      <div class="flex">
        <span>
          <%= guests_icon %>
          <%= flat.number_of_guests %>
        </span>
        <span>
          <%= british_pound_icon %>
          <%= flat.price_per_night %>/night
        </span>
      </div>
    </div>
      <div class="flat-card-actions link-container">
        <%= link_to "More info", flat, class: "action-link" %>
        <%= link_to "Edit", edit_flat_path(flat), class: "edit-link action-link" %>
        <%= link_to "Delete",
          flat_path(flat),
          method: :delete,
          data: {turbo_method: :delete, turbo_confirm: "Are you sure?"},
          class: "remove-link"
        %>
    </div>
  </div>
</div>

app/views/flats/_form.html.erb
<%= simple_form_for(@flat) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <%= f.input :price_per_night %>
    <%= f.input :number_of_guests %>
  </div>

  <div class="form-actions">
  <%= f.submit "Create flat" %>
  </div>

<% end %>

app/views/flats/edit.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="last-right offset-md-4 col-md-4">
      <h1>Editing flat</h1>

      <%= render "form", flat: @flat %>

      <br>

      <div>
        <%= link_to "Show this flat", @flat %> |
        <%= link_to "Back to all flats", flats_path %>
      </div>
    </div>
  </div>
</div>

app/views/flats/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="container mt-3">
  <div class="row">
    <div class="col-12">
      <h1>All our Flats</h1>
      <p>See all <%= @flats.length.to_i %> flats</p>
    </div>
  </div>
    <div class="flat-grid">
      <% @flats.each do |flat| %>
        <%= render flat %>
      <% end %>
  </div>
</div>

app/views/flats/new.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="last-right offset-md-4 col-md-4">
      <h1>New flat</h1>

      <%= render "form", flat: @flat %>

      <br>

      <div>
        <%= link_to "Back to flats", flats_path %>
      </div>
    </div>
  </div>
</div>

app/views/flats/show.html.erb
<div class="container margin-top-negative">
  <div class="row">
    <div class="flat-show-card">
      <h2><%= @flat.name %></h2>
      <p><%= @flat.address %></p>
    </div>
    <div class="flat-show-card">
      <h4>A bit more about this flat...</h4>
      <p><%= @flat.description %></p>
      <div class="flex">
        <span><%= guests_icon %> <%= @flat.number_of_guests %></span>
        <span><%= british_pound_icon %> <%= @flat.price_per_night %>/night</span>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <div class="container-fluid d-flex flex-column pb-1 mb-2">
    <nav class="navbar navbar-light bg-light">
    <a href="/flats" class="d-flex text-dark text-decoration-none">Simple Airbnb</a>
    <%= link_to "Add flat", new_flat_path, :class => "btn btn-outline-primary float-right" %>
  </nav>
</div>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>